# Applications 02


```{r setupapps2, echo=FALSE, message=FALSE}
library(leaflet)
library(magrittr)
library(dplyr)
library(tidyverse)
library(htmlwidgets)
library(DT)
```

```{r run-main-02, message=FALSE, echo=FALSE, warning=FALSE}
#source("./analysis/main.R")
load("map_set.RData")

```

### US IRWIN Incidents per m^2, Created Date of 01/01/2021 - 02/10/2022
```{r ex02, message=FALSE, echo=FALSE, warning=FALSE}

p_popup <- paste0("<strong>",map_set$NAME,"</></br>","<strong>Fires: ", map_set$count,"</strong>",
                  "</></br>","<strong>Fires per m^2: ", map_set$count_p_area,"</strong>");

points_popup <- paste0("<strong>Incident Name: ",m$`IncidentName`,"</></br>","<strong>Discovery Time: ", m$FireDiscoveryDateTime,"</strong>","</></br>","<strong>Containment Time: ", m$`ContainmentDateTime`,"</strong>",
                       "</></br>","<strong>Discovery Acres: ", m$`DiscoveryAcres`,"</strong>", "</></br>","<strong>Daily Acres: ", m$`DailyAcres`,"</strong>");
pal_fun <- colorQuantile("YlOrRd", NULL, n = 6)
leaflet(map_set) %>%
  addProviderTiles(providers$Esri.WorldTopoMap) %>%
  addPolygons(data=map_set,
              stroke = FALSE,
              fillColor = ~pal_fun(map_set$count_p_area),
              fillOpacity = 0.6,
              smoothFactor = 0.5,
              popup = p_popup,
              group = "Counties") %>%
  addMarkers(data=m,group="Points",clusterOptions = markerClusterOptions(),icon =  awesomeIcons(
    icon = 'ios-close',
    iconColor = 'black',
    library = 'ion'), popup = points_popup) %>%
  addLayersControl(overlayGroups = c("Counties", "Points"),
                   options = layersControlOptions(collapsed = FALSE)
                   )
```
### Table US IRWIN Incidents 01/01/2021 - s02/10/2022
```{r table, message=FALSE, echo=FALSE, warning=FALSE}
datatable(map_set %>% 
  dplyr::select(c(NAME,count,count_p_area,sum_final_acres,sum_daily_acres,sum_discovery_acres)
  )
)
```
